version: '3.8'

services:
  web:
    container_name: web
    build: 
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn blog.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./prod.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./prod.db.env

volumes:
  postgres_data: