# Generated by Django 4.0.5 on 2022-07-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_htmltype_remove_article_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='html_file',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='ArticleDetails',
        ),
    ]
