# Generated by Django 4.0.5 on 2022-08-01 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_delete_htmltype_rename_html_file_article_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='article_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', related_query_name='articles', to='article.article'),
        ),
        migrations.AlterField(
            model_name='articlecategory',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', related_query_name='categories', to='article.category'),
        ),
    ]
